POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0MWNiZWI5MDNiNWVmMzFlN2M3ZGNkNyIsImlhdCI6MTY3OTg3MTQ4MCwiZXhwIjoxNjc5ODc1MDgwfQ.HOWiv0pecEX2VnDKB1GJwd8xShZF-Q7PuOwFVr3UkC8

{
    "title":"The downfall of backend",
    "author":"Martin O'Martin",
    "url":"https://misterClean.com",
    "likes":4
}